server:
  port: 9000

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring_db?useUnicode=true&charaterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: spring
    password: spring
  jpa:
    database-platform: org.hibernate.dialect.MariaDB53Dialect
    hibernate:
      ddl-auto: create
  messages:
    basename: exception/exception
    encoding: UTF-8
  jwt:
    secret: govlepel@$&

  social:
    kakao:
      client_id: 50a3601a6e6e16a071f3594877836ce6 # 앱생성시 받은 REST API 키
      redirect: /social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
  url:
    base: http://localhost:9000